"""Add model Conta

Revision ID: 22893bec79a6
Revises: 93da36584ce7
Create Date: 2025-01-31 21:20:02.279030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22893bec79a6'
down_revision = '93da36584ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=150), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('agencia', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=150), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta')
    # ### end Alembic commands ###
