"""campo cpf

Revision ID: c5c028bf1c5b
Revises: 22893bec79a6
Create Date: 2025-01-31 22:06:16.824258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c028bf1c5b'
down_revision = '22893bec79a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=False))
        batch_op.create_unique_constraint('uq_cliente_cpf', ['cpf'])  # Nome da constraint corrigido

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cliente_cpf', type_='unique')  # Nome correto da constraint
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
